server:
  port: 8082

spring:
  application:
    name: maestria-course-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:maestria_courses}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "${spring.security.oauth2.resourceserver.jwt.secret-key}"


logging:
  level:
    org.springframework.security: TRACE